# [邮箱 API 模式选择]
# https://github.com/smanx/freemail
# https://github.com/dreamhunter2333/cloudflare_temp_email
# https://github.com/maillab/cloud-mail
# https://github.com/s12ryt/mail-curl
# 可选值: "imap" / "freemail" / "cloudflare_temp_email" / "cloudmail" / "mail_curl" / "luckmail"
email_api_mode: "cloudflare_temp_email"

# [基础配置: cloudflare_temp_email / imap / cloudmail 共享]
# 你的域名 (支持逗号分隔多域名随机轮换) 如果只有一个域名就只填一个域名

mail_domains: "domain1.com,domain2.xyz,domain3.net"

#二级域名开关
enable_sub_domains: false

sub_domain_count: 1
#域名层级
sub_domain_level: 1
#随机层级开关
random_sub_domain_level: false

ai_service:
  enable_profile: false
  api_base: "http://your-domain.com:8317/v1"
  api_key: ""
  model: "gpt-5"


# 你的临时邮箱 后端API 基础地址 结尾不要/，IMAP和freemail/cloudmail/mail_curl不需要配置此项。注意：用浏览器打开后端api验证是否可访问
gptmail_base: "https://your-domain.com" #是后端访问链接，不是前端访问链接，正常情况浏览器打开访问会显示ok就是对的

# [模式 "cloudflare_temp_email" 专属配置]
# 你的临时邮箱管理员密码
admin_auth: ""

# [模式 "imap" 专属配置] (CF Catch-all 转发接收端)
imap:
  # 默认为gmail IMAP 服务器地址,QQ为imap.qq.com。不建议用QQ
  server: "imap.gmail.com"
  # IMAP 端口
  port: 993
  # 接收转发的真实邮箱账号
  user: ""
  # 16位应用专用密码，谷歌邮箱要去https://myaccount.google.com/apppasswords这里创建专属应用密码
  pass: ""

# [模式 "freemail" 专属]
freemail:
  #访问链接
  api_url: "https://your-domain.com"
  #JWTTOKEN
  api_token: ""
  admin_username: 
  admin_password: 

# [模式 "cloud-mail" 专属配置]
cloudmail:
  #访问链接
  api_url: "https://your-domain.com"
  #管理员邮箱
  admin_email: "admin@your-domain.com"
  admin_password: "你的管理员密码"

# [模式 "mail_curl" 专属配置]
mail_curl:
  #访问链接
  api_base: "https://your-domain.com"
  key: "" # 你的密钥

luckmail:
  api_key: ""
  preferred_domain: ""
  email_type: ms_graph
  variant_mode: ''
  reuse_purchased: true
  tag_id: 
# [代理配置]
# openai注册时代理地址，例子：http://127.0.0.1:7897。如果是国外服务器此项可以不填
default_proxy: ""

# 是否开启注册多线程并发 (true/false)
enable_multi_thread_reg: false    
# 注册时的最大并发线程数 (建议根据你的代理质量调整，不要设置过高)
reg_threads: 10



# Clash 节点智能轮换（本地使用clash软件）
clash_proxy_pool:
  # 【开关】是否在每次注册前自动通过 Clash 切换节点
  enable: false
  # 【核心开关】true=服务器10容器独立推算模式；false=本地单机/单容器模式
  pool_mode: false
  # Clash 的外部控制 API 地址 (注意端口通常是 9090 或 9097)
  api_url: "http://127.0.0.1:9097"
  #true为测速优选，false为随机盲抽。提示：如果A节点一直是最低延迟那么可能每次都是A节点。
  fastest_mode: false
  # 你机场包含所有节点的策略组名称，带有 Emoji 也没关系
  group_name: "节点选择"
  # Clash 的外部控制鉴权秘钥 (Secret)
  secret: "set-your-secret"
  # 用于连接外网测活的本地代理端口 (通常与上方的 default_proxy 保持一致)
  test_proxy_url: ""
  # 节点过滤黑名单：严格剔除包含以下关键词的节点 (如港台地区、说明性节点)
  blacklist:
    - "自动"
    - "故障"
    - "剩余"
    - "到期"
    - "官网"
    - "Traffic"
    - "DIRECT"
    - "REJECT"
    - "港"
    - "HK"
    - "Hongkong"
    - "台"
    - "TW"
    - "Taiwan"
    - "中"
    - "CN"
    - "China"
    - "回国"

warp_proxy_list:
  - "http://127.0.0.1:41001"
  - "http://127.0.0.1:41002"
  - "http://127.0.0.1:41003"
  - "http://127.0.0.1:41004"
  - "http://127.0.0.1:41005"
  - "http://127.0.0.1:41006"
  - "http://127.0.0.1:41007"
  - "http://127.0.0.1:41008"
  - "http://127.0.0.1:41009"
  - "http://127.0.0.1:41010"


# [验证码重发次数配置，默认5次]
max_otp_retries: 5

# [邮箱代理专项配置]
# 【开关】true 表示获取邮箱（谷歌）也用代理，false 表示直连（推荐先试 false）如果是国外服务器此项可以保持false
use_proxy_for_email: false
# 【开关】true 表示在控制台日志中隐藏邮箱域名，false 表示显示完整邮箱
enable_email_masking: true


#注册后等待多少秒在去拿tokens,默认是5-15秒之内
login_delay_min: 20
login_delay_max: 45

# CPA 模式专属配置
cpa_mode:
  # 【开关】true 开启巡检补货上传，false 则只进行常规无限注册
  enable: false
  auto_check: true
  # 【开关】开启 CPA 补货时，是否同时将账号 Token 备份到本地，默认true为备份
  save_to_local: true
  # CPA的访问地址
  api_url: "http://your-domain.com:8317"
  # CPA登陆密码
  api_token: "xxxx"
  # 仓库存量低于此值时触发补货
  min_accounts_threshold: 30
  # 每次触发补货注册的数量
  batch_reg_count: 1
  # 周限额剔除阈值设置 (0-100)
  # 设为 80 代表额度剩余低于 80% 就当作死号剔除，设为 0 代表完全耗尽才剔除。
  min_remaining_weekly_percent: 80
  # 额度耗尽时是否删除 (false 则为不删除，恢复后自动唤醒)
  remove_on_limit_reached: false 
  # 账号彻底死亡(如封号、Token刷新失败)时是否删除 (false 则为不删除，只禁用)
  remove_dead_accounts: false
  # 是否开启刷新token功能
  enable_token_revive: false
  # CPA 仓库巡检的间隔时间，默认每60分钟巡检一次
  check_interval_minutes: 60
  #并发线程数配置，默认 10 线程
  threads: 10

# SUB2APIA配置 参数含义跟CPA相同
sub2api_mode:
  enable: false
  auto_check: true
  save_to_local: true
  api_url: 
  api_key: 
  min_accounts_threshold: 20
  batch_reg_count: 1
  min_remaining_weekly_percent: 80
  remove_on_limit_reached: true
  remove_dead_accounts: true
  enable_token_revive: false
  check_interval_minutes: 60
  threads: 10

hero_sms:
  enabled: false
  api_key: 
  base_url: https://hero-sms.com/stubs/handler_api.php
  country: 50
  service: dr
  auto_pick_country: false
  reuse_phone: true
  max_price: 0.08
  min_balance: 1
  max_tries: 3
  poll_timeout_sec: 120

# 常规量产模式专属配置
normal_mode:
  # 每次循环注册成功或失败后，最短等待时间 (秒)
  sleep_min: 5
  # 每次循环注册成功或失败后，最长等待时间 (秒)
  sleep_max: 30
  # 单次(每批)执行的注册总数
  target_count: 2
# WEB端密码
web_password: admin
#CF账号
cf_api_email: 
#CF KEY
cf_api_key: 